# Site settings

url: "http://adammwilson.github.io"
title: "{ Environmental Science }"
description: "Course Description website for Geography (GEO) 104 Environmental Science at the University at Buffalo, NY"
keywords: "Environmental Science"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-2684666-2"
disqus-shortname: "envsci"
author.name: "Adam M. Wilson"
baseurl: "/EnvSci"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Topics: 'topics'

background-img: {{site.baseurl}}"/img/intro-bg.jpg"

# About variables

me-img: "/img/career/earth.png"

# Career variables

events:
  - image: "/img/career/Literacy.png"
    date: ""
    description: "Environmental Literacy, Science Literacy, and Sustainability"
  - image: "/img/career/Population.png"
    date: ""
    description: "Human Population and Environmental Health"
  - image: "/img/career/Footprint.png"
    date: ""
    description: "Consumption and the Environmental Footprint"
  - image: "/img/career/Ecosystems.png"
    date: ""
    description: "Ecology (Ecosystems, Populations, and Communities)"
  - image: "/img/career/Biodiversity.png"
    date: ""
    description: "Biodiversity and Evolution"
  - image: "/img/career/Water.png"
    date: ""
    description: "Water Resources"
  - image: "/img/career/Food.png"
    date: ""
    description: "Food Resources"
  - image: "/img/career/Fossil.png"
    date: ""
    description: "Fossil Fuels"
  - image: "/img/career/Air.png"
    date: ""
    description: "Air Pollution"
  - image: "/img/career/Renewables.png"
    date: ""
    description: "Renewable Engery"
  - image: "/img/career/Urbanization.png"
    date: ""
    description: "Urbanization"
  - image: "/img/career/Sustainability.png"
    date: ""
    description: "Sustainability and Environmental Policy"

# First image of the Career timeline
career-img: "/img/career/earth.png"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
